#############################################################################
# Makefile for building: JurassicDucks.app/Contents/MacOS/JurassicDucks
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Nov 4 22:45:53 2012
# Project:  JurassicDucks.pro
# Template: app
# Command: /Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile JurassicDucks.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ -I. -I../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtOpenGL -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib -framework QtOpenGL -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		jduckswidget.cpp \
		jduckswindow.cpp \
		jduck.cpp \
		jdcamera.cpp \
		jducks.cpp \
		jdUtility.cpp \
		jdalgorithm.cpp \
		jdplayer.cpp \
		jdlight.cpp \
		jdtext.cpp \
		jdreaderwriter.cpp \
		jdflockdialog.cpp \
		jdgpushader.cpp \
		jdmap.cpp \
		jdtile.cpp \
		jdtree.cpp \
		jdtrees.cpp moc_jduckswidget.cpp \
		moc_jduckswindow.cpp \
		moc_jdflockdialog.cpp
OBJECTS       = main.o \
		jduckswidget.o \
		jduckswindow.o \
		jduck.o \
		jdcamera.o \
		jducks.o \
		jdUtility.o \
		jdalgorithm.o \
		jdplayer.o \
		jdlight.o \
		jdtext.o \
		jdreaderwriter.o \
		jdflockdialog.o \
		jdgpushader.o \
		jdmap.o \
		jdtile.o \
		jdtree.o \
		jdtrees.o \
		moc_jduckswidget.o \
		moc_jduckswindow.o \
		moc_jdflockdialog.o
DIST          = ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		JurassicDucks.pro
QMAKE_TARGET  = JurassicDucks
DESTDIR       = 
TARGET        = JurassicDucks.app/Contents/MacOS/JurassicDucks

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile JurassicDucks.app/Contents/PkgInfo JurassicDucks.app/Contents/Resources/empty.lproj JurassicDucks.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) JurassicDucks.app/Contents/MacOS/ || $(MKDIR) JurassicDucks.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: JurassicDucks.pro  ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/qmake.conf ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile JurassicDucks.pro
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile JurassicDucks.pro

JurassicDucks.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) JurassicDucks.app/Contents || $(MKDIR) JurassicDucks.app/Contents 
	@$(DEL_FILE) JurassicDucks.app/Contents/PkgInfo
	@echo "APPL????" >JurassicDucks.app/Contents/PkgInfo
JurassicDucks.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) JurassicDucks.app/Contents/Resources || $(MKDIR) JurassicDucks.app/Contents/Resources 
	@touch JurassicDucks.app/Contents/Resources/empty.lproj
	
JurassicDucks.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) JurassicDucks.app/Contents || $(MKDIR) JurassicDucks.app/Contents 
	@$(DEL_FILE) JurassicDucks.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,JurassicDucks,g" -e "s,@TYPEINFO@,????,g" ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/Info.plist.app >JurassicDucks.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/JurassicDucks1.0.0 || $(MKDIR) .tmp/JurassicDucks1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/JurassicDucks1.0.0/ && $(COPY_FILE) --parents jduckswidget.h glheaders.h jduckswindow.h jduck.h Vec3.h jdcamera.h jducks.h jdUtility.h jdalgorithm.h jdplayer.h headers.h jdlight.h jdtext.h jdreaderwriter.h jdfactors.h jdflockdialog.h jdgpushader.h jdmap.h Vec4.h jdtile.h Vec2.h jdtree.h jdtrees.h .tmp/JurassicDucks1.0.0/ && $(COPY_FILE) --parents main.cpp jduckswidget.cpp jduckswindow.cpp jduck.cpp jdcamera.cpp jducks.cpp jdUtility.cpp jdalgorithm.cpp jdplayer.cpp jdlight.cpp jdtext.cpp jdreaderwriter.cpp jdflockdialog.cpp jdgpushader.cpp jdmap.cpp jdtile.cpp jdtree.cpp jdtrees.cpp .tmp/JurassicDucks1.0.0/ && (cd `dirname .tmp/JurassicDucks1.0.0` && $(TAR) JurassicDucks1.0.0.tar JurassicDucks1.0.0 && $(COMPRESS) JurassicDucks1.0.0.tar) && $(MOVE) `dirname .tmp/JurassicDucks1.0.0`/JurassicDucks1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/JurassicDucks1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r JurassicDucks.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_jduckswidget.cpp moc_jduckswindow.cpp moc_jdflockdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_jduckswidget.cpp moc_jduckswindow.cpp moc_jdflockdialog.cpp
moc_jduckswidget.cpp: jducks.h \
		jdcamera.h \
		glheaders.h \
		Vec3.h \
		jdplayer.h \
		jdtrees.h \
		headers.h \
		jdtree.h \
		Vec2.h \
		jdlight.h \
		jdtext.h \
		jdgpushader.h \
		jdmap.h \
		Vec4.h \
		jdtile.h \
		jduckswidget.h
	/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ jduckswidget.h -o moc_jduckswidget.cpp

moc_jduckswindow.cpp: jduckswindow.h
	/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ jduckswindow.h -o moc_jduckswindow.cpp

moc_jdflockdialog.cpp: headers.h \
		jdreaderwriter.h \
		jdflockdialog.h
	/Users/rending/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ jdflockdialog.h -o moc_jdflockdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp headers.h \
		jdUtility.h \
		glheaders.h \
		jduckswindow.h \
		jduckswidget.h \
		jducks.h \
		jdcamera.h \
		Vec3.h \
		jdplayer.h \
		jdtrees.h \
		jdtree.h \
		Vec2.h \
		jdlight.h \
		jdtext.h \
		jdgpushader.h \
		jdmap.h \
		Vec4.h \
		jdtile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

jduckswidget.o: jduckswidget.cpp headers.h \
		glheaders.h \
		jduck.h \
		Vec3.h \
		jducks.h \
		jdplayer.h \
		jdtree.h \
		Vec2.h \
		jdtrees.h \
		jdlight.h \
		jdUtility.h \
		jdalgorithm.h \
		jdgpushader.h \
		jdfactors.h \
		jduckswidget.h \
		jdcamera.h \
		jdtext.h \
		jdmap.h \
		Vec4.h \
		jdtile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jduckswidget.o jduckswidget.cpp

jduckswindow.o: jduckswindow.cpp jduckswindow.h \
		jduckswidget.h \
		jducks.h \
		jdcamera.h \
		glheaders.h \
		Vec3.h \
		jdplayer.h \
		jdtrees.h \
		headers.h \
		jdtree.h \
		Vec2.h \
		jdlight.h \
		jdtext.h \
		jdgpushader.h \
		jdmap.h \
		Vec4.h \
		jdtile.h \
		jdfactors.h \
		jduck.h \
		jdflockdialog.h \
		jdreaderwriter.h \
		jdalgorithm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jduckswindow.o jduckswindow.cpp

jduck.o: jduck.cpp glheaders.h \
		jdUtility.h \
		jdalgorithm.h \
		jduck.h \
		Vec3.h \
		jducks.h \
		jdtrees.h \
		headers.h \
		jdtree.h \
		Vec2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jduck.o jduck.cpp

jdcamera.o: jdcamera.cpp jdcamera.h \
		glheaders.h \
		Vec3.h \
		headers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdcamera.o jdcamera.cpp

jducks.o: jducks.cpp jduck.h \
		glheaders.h \
		Vec3.h \
		jducks.h \
		jdplayer.h \
		jdtrees.h \
		headers.h \
		jdtree.h \
		Vec2.h \
		jdtext.h \
		jdalgorithm.h \
		jduckswidget.h \
		jdcamera.h \
		jdlight.h \
		jdgpushader.h \
		jdmap.h \
		Vec4.h \
		jdtile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jducks.o jducks.cpp

jdUtility.o: jdUtility.cpp jdUtility.h \
		glheaders.h \
		jduckswindow.h \
		headers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdUtility.o jdUtility.cpp

jdalgorithm.o: jdalgorithm.cpp jdalgorithm.h \
		jduck.h \
		glheaders.h \
		Vec3.h \
		jducks.h \
		jdtrees.h \
		headers.h \
		jdtree.h \
		Vec2.h \
		jdfactors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdalgorithm.o jdalgorithm.cpp

jdplayer.o: jdplayer.cpp jdplayer.h \
		glheaders.h \
		Vec3.h \
		jducks.h \
		jduck.h \
		headers.h \
		jdalgorithm.h \
		jdtrees.h \
		jdtree.h \
		Vec2.h \
		jdUtility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdplayer.o jdplayer.cpp

jdlight.o: jdlight.cpp jdlight.h \
		glheaders.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdlight.o jdlight.cpp

jdtext.o: jdtext.cpp jdtext.h \
		headers.h \
		jdUtility.h \
		glheaders.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdtext.o jdtext.cpp

jdreaderwriter.o: jdreaderwriter.cpp jdreaderwriter.h \
		headers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdreaderwriter.o jdreaderwriter.cpp

jdflockdialog.o: jdflockdialog.cpp jdflockdialog.h \
		headers.h \
		jdreaderwriter.h \
		jdfactors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdflockdialog.o jdflockdialog.cpp

jdgpushader.o: jdgpushader.cpp jdgpushader.h \
		glheaders.h \
		headers.h \
		jdUtility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdgpushader.o jdgpushader.cpp

jdmap.o: jdmap.cpp jdmap.h \
		headers.h \
		Vec4.h \
		jdtile.h \
		Vec2.h \
		Vec3.h \
		jdtrees.h \
		jdtree.h \
		glheaders.h \
		jdUtility.h \
		jdfactors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdmap.o jdmap.cpp

jdtile.o: jdtile.cpp jdtile.h \
		headers.h \
		Vec2.h \
		Vec3.h \
		jdmap.h \
		Vec4.h \
		jdtrees.h \
		jdtree.h \
		glheaders.h \
		jdUtility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdtile.o jdtile.cpp

jdtree.o: jdtree.cpp jdtree.h \
		Vec2.h \
		Vec3.h \
		headers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdtree.o jdtree.cpp

jdtrees.o: jdtrees.cpp headers.h \
		jdtrees.h \
		jdtree.h \
		Vec2.h \
		Vec3.h \
		jdmap.h \
		Vec4.h \
		jdtile.h \
		jdUtility.h \
		glheaders.h \
		jdfactors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jdtrees.o jdtrees.cpp

moc_jduckswidget.o: moc_jduckswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jduckswidget.o moc_jduckswidget.cpp

moc_jduckswindow.o: moc_jduckswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jduckswindow.o moc_jduckswindow.cpp

moc_jdflockdialog.o: moc_jdflockdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jdflockdialog.o moc_jdflockdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

